swagger: "2.0"
info:
  description: "Documentação referente a API de agendamento de consultas.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Agendamentos"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "lucasrafael654@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "swagger.io"
basePath: "/v2"
tags:
- name: "criar"
  description: "Crie agendamentos"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "consultar"
  description: "Consulte agendamentos"
- name: "cancelar"
  description: "Cancele agendamentos"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /agendamento/criar:
    post:
      tags:
      - "criar"
      summary: "Efetua um novo agendamento."
      description: "Método responsável por efetuar um novo a gendamento de consulta"
      operationId: "criar"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto referente ao agendamento de consulta a ser efetuado"
        required: true
        schema:
          $ref: "#/definitions/Criar"
      responses:
        "201":
          description: "Agendamento efetuado com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Criar"
        "400":
          description: "Dados enviados inválidos"
      security:
        - api_key: []
  /agendamento/{IdAgendamento}/consultar:
    get:
      tags:
      - "consultar"
      summary: "Consulta agendamento com base no ID"
      description: "Método responsável por consultar um agendamento"
      operationId: "ConsultarAgendamento"
      produces:
      - "application/json"
      parameters:
      - name: "IdAgendamento"
        in: "path"
        description: "ID do agendamento a ser consultado."
        required: true
        type: "string"
      responses:
        "200":
          description: "Agendamento encontrado"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Criar"
        "404":
          description: "Nenhum agendamento foi encontrado com o ID informado"
      security:
      - api_key: []
  /agendamento/{IdAgendamento}/cancelar:
    delete:
      tags:
      - "cancelar"
      summary: "Efetua o cancelamento de um agendamento"
      description: "Método responsável por efetuar o cancelamento de um agendamento"
      operationId: "cancelar"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "IdAgendamento"
        description: "ID referente ao agendamento a ser cancelado"
        required: true
        type: "string"
      responses:
        "200":
          description: "Agendamento cancelado com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Criar"
        "404":
          description: "Nenhum agendamento foi encontrado com o ID informado"
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Criar:
    type: "object"
    properties:
      cpf:
        type: "string"
      DataAgendamento:
        type: "string"
        format: "date-time"
      NumeroConvenio:
        type: "string"
      MotivoConsulta:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"